// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDC6NyU48kLZ-RJQQNNVQ7ajak_mAtDCto',
    appId: '1:987873319779:web:8986479801cf7496b75156',
    messagingSenderId: '987873319779',
    projectId: 'to-do-list-29552',
    authDomain: 'to-do-list-29552.firebaseapp.com',
    databaseURL: 'https://to-do-list-29552-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-list-29552.appspot.com',
    measurementId: 'G-9PFPC2EPT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsx7AxCj2elhDSVd4TpXxeBIXWphR62B4',
    appId: '1:987873319779:android:dc6e9bda116724ebb75156',
    messagingSenderId: '987873319779',
    projectId: 'to-do-list-29552',
    databaseURL: 'https://to-do-list-29552-default-rtdb.firebaseio.com',
    storageBucket: 'to-do-list-29552.appspot.com',
  );

}